import time
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver import Keys, ActionChains
# from selenium.webdriver.chrome import webdriver
from selenium.webdriver.common import keys
from selenium.webdriver.common.by import By
import pytest
class Test_youtube_pytest:
    @pytest.fixture(scope="session")
    def setUp(self):
        global driver
        option = Options()
        option.headless = True
        # executable_path = "I:\\Software Testing\\python\\rcvacademy\\Drivers\\chromedriver.exe"
        driver = webdriver.Chrome(options=option,executable_path = "I:\\Software Testing\\python\\rcvacademy\\Drivers\\chromedriver.exe")
        driver.implicitly_wait(15)
        print('Browser launch success.')
        driver.maximize_window()


        yield
        driver.quit()

    # @pytest.mark.skip
    def test_TAB(self,setUp):
        driver.get("https://jqueryui.com/selectable/")
        driver.execute_script("window.scrollTo(0,160)")
        driver.switch_to.frame(0)
        actions=ActionChains(driver)
        item1=driver.find_element(By.XPATH, "//li[normalize-space()='Item 1']")
        item2=driver.find_element(By.XPATH, "//li[normalize-space()='Item 2']")
        item3=driver.find_element(By.XPATH, "//li[normalize-space()='Item 3']")
        item4=driver.find_element(By.XPATH, "//li[normalize-space()='Item 4']")
        item5=driver.find_element(By.XPATH, "//li[normalize-space()='Item 5']")
        item6=driver.find_element(By.XPATH, "//li[normalize-space()='Item 6']")
        item7=driver.find_element(By.XPATH, "//li[normalize-space()='Item 7']")
        # actions.key_up(Keys.CONTROL).click(item7).perform()
        # actions.key_up(Keys.CONTROL).click(item6).perform()
        # actions.key_up(Keys.CONTROL).click(item5).perform()
        # actions.key_up(Keys.CONTROL).click(item4).perform()
        # actions.key_up(Keys.CONTROL).click(item3).perform()
        # actions.key_up(Keys.CONTROL).click(item2).perform()
        # actions.key_up(Keys.CONTROL).click(item1).perform()
        # actions.key_up(Keys.CONTROL).click(item4).perform()
        # actions.key_up(Keys.CONTROL).click(item3).perform()
        # actions.key_up(Keys.CONTROL).click(item2).perform()
        # actions.key_up(Keys.CONTROL).click(item3).perform()
        # actions.key_up(Keys.CONTROL).click(item2).perform()
        # actions.key_up(Keys.CONTROL).click(item4).perform()

        actions.send_keys(Keys.TAB).perform()
        time.sleep(1)
        actions.send_keys(Keys.TAB).perform()
        time.sleep(1)
        actions.send_keys(Keys.TAB).perform()
        time.sleep(1)
        actions.send_keys(Keys.TAB).perform()
        time.sleep(1)
        actions.send_keys(Keys.TAB).perform()
        time.sleep(1)
        actions.send_keys(Keys.TAB).perform()
        time.sleep(1)
        actions.send_keys(Keys.TAB).perform()
        time.sleep(1)
        actions.send_keys(Keys.TAB).perform()
        time.sleep(1)
        actions.send_keys(Keys.TAB).perform()
        time.sleep(1)
        actions.send_keys(Keys.TAB).perform()
        time.sleep(1)
        actions.send_keys(Keys.TAB).perform()
        time.sleep(1)
        actions.send_keys(Keys.TAB).perform()
        time.sleep(1)
        actions.send_keys(Keys.TAB).perform()
        time.sleep(1)
        actions.send_keys(Keys.TAB).perform()
        time.sleep(1)

    def test_END(self,setUp):
        driver.get("https://jqueryui.com/")
        # driver.execute_script("window.scrollTo(0,160)")
        # driver.switch_to.frame(0)
        actions=ActionChains(driver)
        # item1=driver.find_element(By.XPATH, "//li[normalize-space()='Item 1']")
        # item2=driver.find_element(By.XPATH, "//li[normalize-space()='Item 2']")
        # item3=driver.find_element(By.XPATH, "//li[normalize-space()='Item 3']")
        # item4=driver.find_element(By.XPATH, "//li[normalize-space()='Item 4']")
        # item5=driver.find_element(By.XPATH, "//li[normalize-space()='Item 5']")
        # item6=driver.find_element(By.XPATH, "//li[normalize-space()='Item 6']")
        # item7=driver.find_element(By.XPATH, "//li[normalize-space()='Item 7']")
        actions.send_keys(Keys.END).perform()
        time.sleep(2)

    def test_TAB_and_ENTER(self,setUp):
        driver.get("https://jqueryui.com/")
        # driver.execute_script("window.scrollTo(0,160)")
        # driver.switch_to.frame(0)
        actions=ActionChains(driver)
        # item1=driver.find_element(By.XPATH, "//li[normalize-space()='Item 1']")
        # item2=driver.find_element(By.XPATH, "//li[normalize-space()='Item 2']")
        # item3=driver.find_element(By.XPATH, "//li[normalize-space()='Item 3']")
        # item4=driver.find_element(By.XPATH, "//li[normalize-space()='Item 4']")
        # item5=driver.find_element(By.XPATH, "//li[normalize-space()='Item 5']")
        # item6=driver.find_element(By.XPATH, "//li[normalize-space()='Item 6']")
        # item7=driver.find_element(By.XPATH, "//li[normalize-space()='Item 7']")
        actions.send_keys(Keys.TAB).send_keys(Keys.ENTER).perform()

        # actions.send_keys(Keys.ENTER).perform()
        time.sleep(5)

    def test_PAGE_DOWN_and_PAGE_UP(self,setUp):
        driver.get("https://jqueryui.com/")
        # driver.execute_script("window.scrollTo(0,160)")
        # driver.switch_to.frame(0)
        actions=ActionChains(driver)
        # item1=driver.find_element(By.XPATH, "//li[normalize-space()='Item 1']")
        # item2=driver.find_element(By.XPATH, "//li[normalize-space()='Item 2']")
        # item3=driver.find_element(By.XPATH, "//li[normalize-space()='Item 3']")
        # item4=driver.find_element(By.XPATH, "//li[normalize-space()='Item 4']")
        # item5=driver.find_element(By.XPATH, "//li[normalize-space()='Item 5']")
        # item6=driver.find_element(By.XPATH, "//li[normalize-space()='Item 6']")
        # item7=driver.find_element(By.XPATH, "//li[normalize-space()='Item 7']")
        actions.send_keys(Keys.PAGE_DOWN).perform()
        time.sleep(2)
        actions.send_keys(Keys.PAGE_DOWN).perform()
        time.sleep(2)
        actions.send_keys(Keys.PAGE_UP).perform()
        time.sleep(2)

    def test_DOWN(self,setUp):
        driver.get("https://jqueryui.com/")
        # driver.execute_script("window.scrollTo(0,160)")
        # driver.switch_to.frame(0)
        actions=ActionChains(driver)
        # item1=driver.find_element(By.XPATH, "//li[normalize-space()='Item 1']")
        # item2=driver.find_element(By.XPATH, "//li[normalize-space()='Item 2']")
        # item3=driver.find_element(By.XPATH, "//li[normalize-space()='Item 3']")
        # item4=driver.find_element(By.XPATH, "//li[normalize-space()='Item 4']")
        # item5=driver.find_element(By.XPATH, "//li[normalize-space()='Item 5']")
        # item6=driver.find_element(By.XPATH, "//li[normalize-space()='Item 6']")
        # item7=driver.find_element(By.XPATH, "//li[normalize-space()='Item 7']")
        actions.send_keys(Keys.DOWN).perform()
        time.sleep(1)
        actions.send_keys(Keys.DOWN).perform()
        time.sleep(1)
        actions.send_keys(Keys.DOWN).perform()
        time.sleep(1)
        actions.send_keys(Keys.DOWN).perform()
        time.sleep(1)
        actions.send_keys(Keys.DOWN).perform()
        time.sleep(1)
        actions.send_keys(Keys.DOWN).perform()
        time.sleep(1)
        actions.send_keys(Keys.DOWN).perform()
        time.sleep(1)
        actions.send_keys(Keys.UP).perform()
        time.sleep(1)
        actions.send_keys(Keys.UP).perform()
        time.sleep(1)
        actions.send_keys(Keys.UP).perform()
        time.sleep(1)
        actions.send_keys(Keys.UP).perform()
        time.sleep(1)
        actions.send_keys(Keys.UP).perform()
        time.sleep(1)

    def test_click_alt_ENTER(self,setUp):
        driver.get("https://google.com/")
        driver.find_element(By.XPATH, "//input[@title='সার্চ করুন']").send_keys("myone")
        # driver.execute_script("window.scrollTo(0,160)")
        # driver.switch_to.frame(0)
        actions=ActionChains(driver)
        # item1=driver.find_element(By.XPATH, "//li[normalize-space()='Item 1']")
        # item2=driver.find_element(By.XPATH, "//li[normalize-space()='Item 2']")
        # item3=driver.find_element(By.XPATH, "//li[normalize-space()='Item 3']")
        # item4=driver.find_element(By.XPATH, "//li[normalize-space()='Item 4']")
        # item5=driver.find_element(By.XPATH, "//li[normalize-space()='Item 5']")
        # item6=driver.find_element(By.XPATH, "//li[normalize-space()='Item 6']")
        # item7=driver.find_element(By.XPATH, "//li[normalize-space()='Item 7']")
        actions.send_keys(Keys.ENTER).perform()
        time.sleep(2)
        actions.key_down(Keys.CONTROL).send_keys("a").perform()
        time.sleep(5)

    def test_click_alt_ENTER01(self, setUp):
        driver.get("https://google.com/")
        actions = ActionChains(driver)
        search=driver.find_element(By.XPATH, "//input[@title='সার্চ করুন']")
        search.send_keys("robotrobotrobot")
        time.sleep(3)
        # driver.execute_script("window.scrollTo(0,160)")
        # driver.switch_to.frame(0)

        # item1=driver.find_element(By.XPATH, "//li[normalize-space()='Item 1']")
        # item2=driver.find_element(By.XPATH, "//li[normalize-space()='Item 2']")
        # item3=driver.find_element(By.XPATH, "//li[normalize-space()='Item 3']")
        # item4=driver.find_element(By.XPATH, "//li[normalize-space()='Item 4']")
        # item5=driver.find_element(By.XPATH, "//li[normalize-space()='Item 5']")
        # item6=driver.find_element(By.XPATH, "//li[normalize-space()='Item 6']")
        # item7=driver.find_element(By.XPATH, "//li[normalize-space()='Item 7']")


        actions.key_down(Keys.CONTROL).send_keys("a").key_up(Keys.CONTROL).perform()  # all data select
        time.sleep(2)
        actions.key_down(Keys.CONTROL).send_keys("c").key_up(Keys.CONTROL).perform()  # selected data copy
        actions.key_down(Keys.BACK_SPACE).perform()  # selected data clear
        time.sleep(2)
        # actions.key_down(Keys.BACKSPACE).perform()  # selectesd data clear
        actions.key_down(Keys.CONTROL).send_keys("v").key_up(Keys.CONTROL).perform()  # selected data past
        # actions.double_click(search).perform()
        # actions.key_down(Keys.CONTROL).send_keys("p").perform()
        time.sleep(3)

    def test_SHIFT(self,setUp):
        driver.get("https://google.com/")
        actions = ActionChains(driver)
        search = driver.find_element(By.XPATH, "//input[@title='সার্চ করুন']")
        actions.key_down(Keys.SHIFT).send_keys("abcdefghijk").key_up(Keys.SHIFT).send_keys("abcdef").send_keys("xyz").key_down(Keys.SHIFT).send_keys("lkjhgfdsa").perform()
        time.sleep(2)
        actions.key_up(Keys.SHIFT).send_keys("poiuytrewq").perform()
        # driver.execute_script("window.scrollTo(0,160)")
        # driver.switch_to.frame(0)
        # actions=ActionChains(driver)
        # item1=driver.find_element(By.XPATH, "//li[normalize-space()='Item 1']")
        # item2=driver.find_element(By.XPATH, "//li[normalize-space()='Item 2']")
        # item3=driver.find_element(By.XPATH, "//li[normalize-space()='Item 3']")
        # item4=driver.find_element(By.XPATH, "//li[normalize-space()='Item 4']")
        # item5=driver.find_element(By.XPATH, "//li[normalize-space()='Item 5']")
        # item6=driver.find_element(By.XPATH, "//li[normalize-space()='Item 6']")
        # item7=driver.find_element(By.XPATH, "//li[normalize-space()='Item 7']")
        # actions.send_keys(Keys.).perform()
        time.sleep(2)

    def test_ARROW_UP_DOWN(self,setUp):
        driver.get("https://jqueryui.com/")
        # driver.execute_script("window.scrollTo(0,160)")
        # driver.switch_to.frame(0)
        actions=ActionChains(driver)
        # item1=driver.find_element(By.XPATH, "//li[normalize-space()='Item 1']")
        # item2=driver.find_element(By.XPATH, "//li[normalize-space()='Item 2']")
        # item3=driver.find_element(By.XPATH, "//li[normalize-space()='Item 3']")
        # item4=driver.find_element(By.XPATH, "//li[normalize-space()='Item 4']")
        # item5=driver.find_element(By.XPATH, "//li[normalize-space()='Item 5']")
        # item6=driver.find_element(By.XPATH, "//li[normalize-space()='Item 6']")
        # item7=driver.find_element(By.XPATH, "//li[normalize-space()='Item 7']")
        actions.key_down(Keys.ARROW_DOWN).send_keys(Keys.ARROW_DOWN).send_keys(Keys.ARROW_DOWN).send_keys(Keys.ARROW_DOWN).send_keys(Keys.ARROW_DOWN).send_keys(Keys.ARROW_DOWN).send_keys(Keys.ARROW_DOWN).perform()
        time.sleep(2)
        actions.key_up(Keys.ARROW_UP).send_keys(Keys.ARROW_UP).send_keys(Keys.ARROW_UP).perform()
        time.sleep(2)
        actions.key_down(Keys.ARROW_RIGHT).perform()
        time.sleep(2)

    def test_SPACE(self,setUp):
        driver.get("https://google.com/")
        actions = ActionChains(driver)
        search = driver.find_element(By.XPATH, "//input[@title='সার্চ করুন']")
        actions.key_down(Keys.SHIFT).send_keys("gp").key_up(Keys.SHIFT).send_keys(Keys.SPACE).key_down(Keys.SHIFT).send_keys("bd").perform()
        # driver.execute_script("window.scrollTo(0,160)")
        # driver.switch_to.frame(0)
        # actions=ActionChains(driver)
        # item1=driver.find_element(By.XPATH, "//li[normalize-space()='Item 1']")
        # item2=driver.find_element(By.XPATH, "//li[normalize-space()='Item 2']")
        # item3=driver.find_element(By.XPATH, "//li[normalize-space()='Item 3']")
        # item4=driver.find_element(By.XPATH, "//li[normalize-space()='Item 4']")
        # item5=driver.find_element(By.XPATH, "//li[normalize-space()='Item 5']")
        # item6=driver.find_element(By.XPATH, "//li[normalize-space()='Item 6']")
        # item7=driver.find_element(By.XPATH, "//li[normalize-space()='Item 7']")
        # actions.key_down(Keys.CONTROL).send_keys("a").perform()
        # time.sleep(3)
        actions.pause(3).perform()
        # time.sleep(5)



